version: 2.1

orbs:
  ruby: circleci/ruby@1.0.2

docker_sbt: &docker_sbt
  docker:
    - image: circleci/openjdk:8-jdk
      environment:
        DEBIAN_FRONTEND: noninteractive
        SBT_OPTS: -Xms256m -Xmx756G -XX:+CMSClassUnloadingEnabled -XX:+UseSerialGC -XX:MaxMetaspaceSize=2G
        DISABLE_SCALAFMT: true
  working_directory: ~/repo
  environment:
    JVM_OPTS: -Xmx3200m

cache_save: &cache_save
  save_cache:
    paths:
      - ~/.m2
      - ~/.sbt
      - ~/.ivy2/cache
    key: v1-{{ checksum "build.sbt" }}

cache_restore: &cache_restore
  restore_cache:
    keys:
      - v1-{{ checksum "build.sbt" }}
      - v1-

commands:
  microsite:
    description: "Execute sbt microsite commands"
    parameters:
      command: {type: string}
    steps:
      - checkout
      - *cache_restore
      - add_ssh_keys:
          fingerprints: "dc:08:4f:54:9c:ba:9d:1f:7f:e1:ec:a1:42:a1:d5:55"
      - ruby/install:
          version: '2.7'
      - run:
          name: Install Jekyll
          command: gem install jekyll
      - run:
          name: Configure Git
          command: |
            git config --global user.email '<>'
            git config --global user.name "CircleCI"
            git config --global push.default simple
      - run:
          name: Deploy microsite
          command: sbt docs/<< parameters.command >>

jobs:
  microsite_compile:
    <<: *docker_sbt
    steps:
      - microsite:
          command: makeMicrosite

  microsite_publish:
    <<: *docker_sbt
    steps:
      - microsite:
          command: publishMicrosite

  release:
    <<: *docker_sbt
    steps:
      - checkout
      - *cache_restore
      - run:
          name: Release
          command: |
            set -e
            tags=`git describe --tags`
            sbt ';set version in ThisBuild := "'${tags}'"; test; publish'
      - *cache_save

  test:
    <<: *docker_sbt
    steps:
      - checkout
      - *cache_restore
      - run:
          name: Test
          command: sbt test
      - *cache_save

workflows:
  version: 2
  master-build:
    jobs:
      - microsite_publish:
          filters: {branches: {only: master}}
      - release:
          filters:
            tags:
              only: /^([0-9\\.]+)$/
            branches:
              ignore: /.*/
  pr-build:
    jobs:
      - microsite_compile:
          filters: {branches: {ignore: master}}
      - test:
          filters: {branches: {ignore: master}}
