version: 2

docker_sbt: &docker_sbt
  docker:
    - image: circleci/openjdk:8-jdk
      environment:
        DEBIAN_FRONTEND: noninteractive
        SBT_OPTS: -Xms256m -Xmx756G -XX:+CMSClassUnloadingEnabled -XX:+UseSerialGC -XX:MaxMetaspaceSize=2G
        DISABLE_SCALAFMT: true
  working_directory: ~/repo
  environment:
    JVM_OPTS: -Xmx3200m

cache_save: &cache_save
  save_cache:
    paths:
      - ~/.m2
      - ~/.sbt
      - ~/.ivy2/cache
    key: v1-{{ checksum "build.sbt" }}

cache_restore: &cache_restore
  restore_cache:
    keys:
      - v1-{{ checksum "build.sbt" }}
      - v1-
jobs:
  release:
    <<: *docker_sbt
    steps:
      - checkout
      - *cache_restore
      - run:
          name: Release
          command: |
            set -e
            tags=`git describe --tags`
            sbt ';set version in ThisBuild := "'${tags}'"; test; publish'
      - *cache_save

  test:
    <<: *docker_sbt
    steps:
      - checkout
      - *cache_restore
      - run:
          name: Test
          command: sbt test
      - *cache_save

workflows:
  version: 2
  master-build:
    jobs:
      - release:
          filters:
            tags:
              only: /^([0-9\\.]+)$/
            branches:
              ignore: /.*/
  pr-build:
    jobs:
      - test:
          filters: {branches: {ignore: master}}
